(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (company-emacs-eclim eclim treepy graphql sicp xterm-color shell-pop rainbow-mode rainbow-identifiers multi-term ibuffer-projectile eshell-z eshell-prompt-extras esh-help engine-mode deft color-identifiers-mode flyspell-correct-ivy counsel swiper ivy ox-twbs ox-gfm org-plus-contrib skewer-mode simple-httpd json-snatcher json-reformat yasnippet multiple-cursors js2-mode hydra parent-mode projectile haml-mode pkg-info epl flx magit magit-popup git-commit ghub with-editor smartparens iedit anzu evil goto-chg highlight web-completion-data dash-functional tern go-mode company markdown-mode bind-map bind-key memoize helm avy helm-core async auto-complete popup f s dash sql-indent vmd-mode toml-mode racer flycheck-rust cargo rust-mode youdao-dictionary names chinese-word-at-point reveal-in-osx-finder pbcopy osx-trash osx-dictionary launchctl flyspell-correct-helm flyspell-correct flycheck-pos-tip pos-tip flycheck auto-dictionary unfill mwim phpunit phpcbf php-extras php-auto-yasnippets drupal-mode latland-theme powerline yapfify pyvenv pytest pyenv-mode py-isort pip-requirements live-py-mode hy-mode helm-pydoc cython-mode company-anaconda anaconda-mode pythonic org-projectile org-category-capture org-present org-pomodoro alert log4e gntp org-mime org-download htmlize gnuplot helm-gtags helm-gitignore helm-css-scss cnfonts wilso-theme macrostep helm-themes helm-swoop helm-projectile helm-mode-manager helm-flx helm-descbinds helm-ag elisp-slime-nav auto-compile packed ace-jump-helm-line yaml-mode ws-butler winum which-key wgrep web-mode web-beautify volatile-highlights vi-tilde-fringe uuidgen use-package toc-org tagedit spaceline smex smeargle slim-mode scss-mode sass-mode restart-emacs request rainbow-delimiters pug-mode popwin php-mode persp-mode pcre2el paradox origami orgit org-bullets open-junk-file neotree move-text mmm-mode markdown-toc magit-gitflow lorem-ipsum livid-mode linum-relative link-hint json-mode js2-refactor js-doc ivy-hydra indent-guide hungry-delete hl-todo highlight-parentheses highlight-numbers highlight-indentation helm-make google-translate golden-ratio go-guru go-eldoc gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link gh-md ggtags fuzzy flx-ido fill-column-indicator fcitx fancy-battery eyebrowse expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-search-highlight-persist evil-numbers evil-nerd-commenter evil-mc evil-matchit evil-magit evil-lisp-state evil-indent-plus evil-iedit-state evil-exchange evil-escape evil-ediff evil-args evil-anzu eval-sexp-fu emmet-mode dumb-jump diminish define-word csv-mode counsel-projectile company-web company-tern company-statistics company-go column-enforce-mode coffee-mode clean-aindent-mode carbon-now-sh auto-highlight-symbol all-the-icons aggressive-indent adaptive-wrap ace-window ace-link ac-ispell)))
 '(spacemacs-theme-custom-colors (quote ((comment-bg . "#292b2e")))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
